# Project: Project1
# Makefile created by Dev-C++ 4.9.9.2

CPP  = g++.exe
CC   = gcc.exe
WINDRES = windres.exe
RES  = 
OBJ  = gameEngine.o $(RES)
LINKOBJ  = gameEngine.o $(RES)
LIBS =  -L"lib" -L"./lib" -lmingw32 -lSDLmain -lSDL -lSDL_mixer -lSDL_ttf  
INCS =  -I"include"  -I"./include" 
CXXINCS =  -I"lib/gcc/mingw32/3.4.2/include"  -I"include/c++/3.4.2/backward"  -I"include/c++/3.4.2/mingw32"  -I"include/c++/3.4.2"  -I"include"  -I"./include" 
BIN  = game/pacman.exe
CXXFLAGS = $(CXXINCS)  
CFLAGS = $(INCS)  
RM = rm -f

.PHONY: all all-before all-after clean clean-custom

all: all-before game/pacman.exe all-after


clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o "game\pacman.exe" $(LIBS)

gameEngine.o: gameEngine.cpp
	$(CPP) -c gameEngine.cpp -o gameEngine.o $(CXXFLAGS)
